version: '3.8'

services:
  mon-environnement-data:
    build: .  # <-- AJOUTE CETTE LIGNE ICI
    image: mon_airflow_spark
    container_name: airflow_spark_lab
    command: airflow standalone
    environment:
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0 # Règle ton problème de localhost
      - AIRFLOW__CORE__LOAD_EXAMPLES=False # Allège l'interface
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./jobs:/opt/airflow/jobs